//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersWcf
{
    using System.Runtime.Serialization;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicDataRequest", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities.AppLevel")]
    public partial class BasicDataRequest : object
    {
        
        private int IntIdField;
        
        private string InvokeAppField;
        
        private string StrIdField;
        
        private string TokenField;
        
        private string UserNameOrEmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntId
        {
            get
            {
                return this.IntIdField;
            }
            set
            {
                this.IntIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvokeApp
        {
            get
            {
                return this.InvokeAppField;
            }
            set
            {
                this.InvokeAppField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrId
        {
            get
            {
                return this.StrIdField;
            }
            set
            {
                this.StrIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserNameOrEmail
        {
            get
            {
                return this.UserNameOrEmailField;
            }
            set
            {
                this.UserNameOrEmailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityClass", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UsersWcf.UserAccess))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UsersWcf.Role))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UsersWcf.App))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UsersWcf.Module))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UsersWcf.User))]
    public partial class EntityClass : object
    {
        
        private string InvokeAppIdField;
        
        private string MessageErrorField;
        
        private string TokenSessionField;
        
        private string UserNameByRequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvokeAppId
        {
            get
            {
                return this.InvokeAppIdField;
            }
            set
            {
                this.InvokeAppIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageError
        {
            get
            {
                return this.MessageErrorField;
            }
            set
            {
                this.MessageErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenSession
        {
            get
            {
                return this.TokenSessionField;
            }
            set
            {
                this.TokenSessionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserNameByRequest
        {
            get
            {
                return this.UserNameByRequestField;
            }
            set
            {
                this.UserNameByRequestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccess", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities")]
    public partial class UserAccess : UsersWcf.EntityClass
    {
        
        private System.Nullable<int> AttemptsToGetLoginWrongField;
        
        private System.Nullable<System.DateTime> ExpirationDateField;
        
        private System.Nullable<bool> IsBlockedField;
        
        private System.Nullable<bool> IsVerifiedField;
        
        private System.DateTime LastUpdateField;
        
        private UsersWcf.Role[] ListRolesField;
        
        private string PassField;
        
        private string RoleIdField;
        
        private UsersWcf.User UserField;
        
        private System.Nullable<int> UserAccessIdField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AttemptsToGetLoginWrong
        {
            get
            {
                return this.AttemptsToGetLoginWrongField;
            }
            set
            {
                this.AttemptsToGetLoginWrongField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsBlocked
        {
            get
            {
                return this.IsBlockedField;
            }
            set
            {
                this.IsBlockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsVerified
        {
            get
            {
                return this.IsVerifiedField;
            }
            set
            {
                this.IsVerifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsersWcf.Role[] ListRoles
        {
            get
            {
                return this.ListRolesField;
            }
            set
            {
                this.ListRolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass
        {
            get
            {
                return this.PassField;
            }
            set
            {
                this.PassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsersWcf.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserAccessId
        {
            get
            {
                return this.UserAccessIdField;
            }
            set
            {
                this.UserAccessIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities")]
    public partial class Role : UsersWcf.EntityClass
    {
        
        private UsersWcf.App AppField;
        
        private UsersWcf.Module[] ListAppModulesField;
        
        private UsersWcf.Module[] ListModulesField;
        
        private string RoleIdField;
        
        private string RoleNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsersWcf.App App
        {
            get
            {
                return this.AppField;
            }
            set
            {
                this.AppField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsersWcf.Module[] ListAppModules
        {
            get
            {
                return this.ListAppModulesField;
            }
            set
            {
                this.ListAppModulesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsersWcf.Module[] ListModules
        {
            get
            {
                return this.ListModulesField;
            }
            set
            {
                this.ListModulesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="App", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities")]
    public partial class App : UsersWcf.EntityClass
    {
        
        private System.Nullable<bool> AllowExpPassField;
        
        private string AppIdField;
        
        private string AppNameField;
        
        private System.Nullable<int> DaysToExpPassField;
        
        private System.Nullable<int> MaxAttemptsToGetLoginField;
        
        private string PrivateKeyField;
        
        private System.Nullable<int> TokenLifeTimeField;
        
        private string URLActivationUserField;
        
        private string URLResetPassField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AllowExpPass
        {
            get
            {
                return this.AllowExpPassField;
            }
            set
            {
                this.AllowExpPassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppId
        {
            get
            {
                return this.AppIdField;
            }
            set
            {
                this.AppIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName
        {
            get
            {
                return this.AppNameField;
            }
            set
            {
                this.AppNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DaysToExpPass
        {
            get
            {
                return this.DaysToExpPassField;
            }
            set
            {
                this.DaysToExpPassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxAttemptsToGetLogin
        {
            get
            {
                return this.MaxAttemptsToGetLoginField;
            }
            set
            {
                this.MaxAttemptsToGetLoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateKey
        {
            get
            {
                return this.PrivateKeyField;
            }
            set
            {
                this.PrivateKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TokenLifeTime
        {
            get
            {
                return this.TokenLifeTimeField;
            }
            set
            {
                this.TokenLifeTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URLActivationUser
        {
            get
            {
                return this.URLActivationUserField;
            }
            set
            {
                this.URLActivationUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URLResetPass
        {
            get
            {
                return this.URLResetPassField;
            }
            set
            {
                this.URLResetPassField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Module", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities")]
    public partial class Module : UsersWcf.EntityClass
    {
        
        private UsersWcf.App AppField;
        
        private string IconField;
        
        private System.Nullable<bool> IsViewField;
        
        private System.DateTime LastUpdateField;
        
        private System.Nullable<bool> ModifyingField;
        
        private string ModuleIdField;
        
        private string ModuleNameField;
        
        private System.Nullable<bool> ReadingField;
        
        private string RoleIdField;
        
        private string StyleField;
        
        private string URLField;
        
        private System.Nullable<bool> WritingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsersWcf.App App
        {
            get
            {
                return this.AppField;
            }
            set
            {
                this.AppField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icon
        {
            get
            {
                return this.IconField;
            }
            set
            {
                this.IconField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsView
        {
            get
            {
                return this.IsViewField;
            }
            set
            {
                this.IsViewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Modifying
        {
            get
            {
                return this.ModifyingField;
            }
            set
            {
                this.ModifyingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleId
        {
            get
            {
                return this.ModuleIdField;
            }
            set
            {
                this.ModuleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName
        {
            get
            {
                return this.ModuleNameField;
            }
            set
            {
                this.ModuleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Reading
        {
            get
            {
                return this.ReadingField;
            }
            set
            {
                this.ReadingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style
        {
            get
            {
                return this.StyleField;
            }
            set
            {
                this.StyleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL
        {
            get
            {
                return this.URLField;
            }
            set
            {
                this.URLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Writing
        {
            get
            {
                return this.WritingField;
            }
            set
            {
                this.WritingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities")]
    public partial class User : UsersWcf.EntityClass
    {
        
        private System.Nullable<int> CompanyIdField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string IdField;
        
        private string LastNameField;
        
        private System.DateTime LastUpdateField;
        
        private UsersWcf.UserAccess[] LoginsField;
        
        private string TypeIdField;
        
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsersWcf.UserAccess[] Logins
        {
            get
            {
                return this.LoginsField;
            }
            set
            {
                this.LoginsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeId
        {
            get
            {
                return this.TypeIdField;
            }
            set
            {
                this.TypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsersWcf.IUsers")]
    public interface IUsers
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/GetUser", ReplyAction="http://tempuri.org/IUsers/GetUserResponse")]
        System.Threading.Tasks.Task<UsersWcf.User> GetUserAsync(UsersWcf.BasicDataRequest filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/GetUserAccessByCompanyID", ReplyAction="http://tempuri.org/IUsers/GetUserAccessByCompanyIDResponse")]
        System.Threading.Tasks.Task<UsersWcf.UserAccess> GetUserAccessByCompanyIDAsync(UsersWcf.BasicDataRequest filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/GetUserManager", ReplyAction="http://tempuri.org/IUsers/GetUserManagerResponse")]
        System.Threading.Tasks.Task<bool> GetUserManagerAsync(string AdmUser, string AdmPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/ValidateUserManager", ReplyAction="http://tempuri.org/IUsers/ValidateUserManagerResponse")]
        System.Threading.Tasks.Task<int> ValidateUserManagerAsync(System.Guid MySessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/CreateSessionManager", ReplyAction="http://tempuri.org/IUsers/CreateSessionManagerResponse")]
        System.Threading.Tasks.Task<bool> CreateSessionManagerAsync(System.Guid NewGuid, string UserNameAdmin, string IPAddress, int CompanyID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/GetUsers", ReplyAction="http://tempuri.org/IUsers/GetUsersResponse")]
        System.Threading.Tasks.Task<UsersWcf.User[]> GetUsersAsync(UsersWcf.User filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/GetUserAccess", ReplyAction="http://tempuri.org/IUsers/GetUserAccessResponse")]
        System.Threading.Tasks.Task<UsersWcf.UserAccess> GetUserAccessAsync(int userAccessId, string token, string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/GetAllUserAccess", ReplyAction="http://tempuri.org/IUsers/GetAllUserAccessResponse")]
        System.Threading.Tasks.Task<UsersWcf.UserAccess[]> GetAllUserAccessAsync(UsersWcf.UserAccess filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/CreateUser", ReplyAction="http://tempuri.org/IUsers/CreateUserResponse")]
        System.Threading.Tasks.Task<UsersWcf.User> CreateUserAsync(UsersWcf.UserAccess filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/CreateOnlyUser", ReplyAction="http://tempuri.org/IUsers/CreateOnlyUserResponse")]
        System.Threading.Tasks.Task<UsersWcf.User> CreateOnlyUserAsync(UsersWcf.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/UpdateUser", ReplyAction="http://tempuri.org/IUsers/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(UsersWcf.User filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/CreateUserAccess", ReplyAction="http://tempuri.org/IUsers/CreateUserAccessResponse")]
        System.Threading.Tasks.Task<bool> CreateUserAccessAsync(UsersWcf.UserAccess password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/UpdateUserAccess", ReplyAction="http://tempuri.org/IUsers/UpdateUserAccessResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAccessAsync(UsersWcf.UserAccess userAccess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/SetPassword", ReplyAction="http://tempuri.org/IUsers/SetPasswordResponse")]
        System.Threading.Tasks.Task<bool> SetPasswordAsync(UsersWcf.UserAccess pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/DeleteUser", ReplyAction="http://tempuri.org/IUsers/DeleteUserResponse")]
        System.Threading.Tasks.Task<int> DeleteUserAsync(UsersWcf.User userToDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/DeleteUserAccess", ReplyAction="http://tempuri.org/IUsers/DeleteUserAccessResponse")]
        System.Threading.Tasks.Task<int> DeleteUserAccessAsync(UsersWcf.UserAccess userToDelete);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IUsersChannel : UsersWcf.IUsers, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class UsersClient : System.ServiceModel.ClientBase<UsersWcf.IUsers>, UsersWcf.IUsers
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UsersClient(EndpointConfiguration endpointConfiguration) : 
                base(UsersClient.GetBindingForEndpoint(endpointConfiguration), UsersClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsersClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UsersClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsersClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UsersClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<UsersWcf.User> GetUserAsync(UsersWcf.BasicDataRequest filters)
        {
            return base.Channel.GetUserAsync(filters);
        }
        
        public System.Threading.Tasks.Task<UsersWcf.UserAccess> GetUserAccessByCompanyIDAsync(UsersWcf.BasicDataRequest filters)
        {
            return base.Channel.GetUserAccessByCompanyIDAsync(filters);
        }
        
        public System.Threading.Tasks.Task<bool> GetUserManagerAsync(string AdmUser, string AdmPassword)
        {
            return base.Channel.GetUserManagerAsync(AdmUser, AdmPassword);
        }
        
        public System.Threading.Tasks.Task<int> ValidateUserManagerAsync(System.Guid MySessionID)
        {
            return base.Channel.ValidateUserManagerAsync(MySessionID);
        }
        
        public System.Threading.Tasks.Task<bool> CreateSessionManagerAsync(System.Guid NewGuid, string UserNameAdmin, string IPAddress, int CompanyID)
        {
            return base.Channel.CreateSessionManagerAsync(NewGuid, UserNameAdmin, IPAddress, CompanyID);
        }
        
        public System.Threading.Tasks.Task<UsersWcf.User[]> GetUsersAsync(UsersWcf.User filters)
        {
            return base.Channel.GetUsersAsync(filters);
        }
        
        public System.Threading.Tasks.Task<UsersWcf.UserAccess> GetUserAccessAsync(int userAccessId, string token, string appId)
        {
            return base.Channel.GetUserAccessAsync(userAccessId, token, appId);
        }
        
        public System.Threading.Tasks.Task<UsersWcf.UserAccess[]> GetAllUserAccessAsync(UsersWcf.UserAccess filters)
        {
            return base.Channel.GetAllUserAccessAsync(filters);
        }
        
        public System.Threading.Tasks.Task<UsersWcf.User> CreateUserAsync(UsersWcf.UserAccess filters)
        {
            return base.Channel.CreateUserAsync(filters);
        }
        
        public System.Threading.Tasks.Task<UsersWcf.User> CreateOnlyUserAsync(UsersWcf.User user)
        {
            return base.Channel.CreateOnlyUserAsync(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(UsersWcf.User filters)
        {
            return base.Channel.UpdateUserAsync(filters);
        }
        
        public System.Threading.Tasks.Task<bool> CreateUserAccessAsync(UsersWcf.UserAccess password)
        {
            return base.Channel.CreateUserAccessAsync(password);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAccessAsync(UsersWcf.UserAccess userAccess)
        {
            return base.Channel.UpdateUserAccessAsync(userAccess);
        }
        
        public System.Threading.Tasks.Task<bool> SetPasswordAsync(UsersWcf.UserAccess pass)
        {
            return base.Channel.SetPasswordAsync(pass);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserAsync(UsersWcf.User userToDelete)
        {
            return base.Channel.DeleteUserAsync(userToDelete);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserAccessAsync(UsersWcf.UserAccess userToDelete)
        {
            return base.Channel.DeleteUserAccessAsync(userToDelete);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUsers))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IUsers))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUsers))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.55.170/Cenet.Auth.Service.Wcf/Svc/Users.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IUsers))
            {
                return new System.ServiceModel.EndpointAddress("https://win2019-20.cenet2000/Cenet.Auth.Service.Wcf/Svc/Users.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUsers,
            
            BasicHttpsBinding_IUsers,
        }
    }
}
