//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticatorWcf
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityClass", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AuthenticatorWcf.Role))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AuthenticatorWcf.App))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AuthenticatorWcf.Module))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AuthenticatorWcf.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AuthenticatorWcf.UserAccess))]
    public partial class EntityClass : object
    {
        
        private string InvokeAppIdField;
        
        private string MessageErrorField;
        
        private string TokenSessionField;
        
        private string UserNameByRequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvokeAppId
        {
            get
            {
                return this.InvokeAppIdField;
            }
            set
            {
                this.InvokeAppIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageError
        {
            get
            {
                return this.MessageErrorField;
            }
            set
            {
                this.MessageErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenSession
        {
            get
            {
                return this.TokenSessionField;
            }
            set
            {
                this.TokenSessionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserNameByRequest
        {
            get
            {
                return this.UserNameByRequestField;
            }
            set
            {
                this.UserNameByRequestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities")]
    public partial class Role : AuthenticatorWcf.EntityClass
    {
        
        private AuthenticatorWcf.App AppField;
        
        private AuthenticatorWcf.Module[] ListAppModulesField;
        
        private AuthenticatorWcf.Module[] ListModulesField;
        
        private string RoleIdField;
        
        private string RoleNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticatorWcf.App App
        {
            get
            {
                return this.AppField;
            }
            set
            {
                this.AppField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticatorWcf.Module[] ListAppModules
        {
            get
            {
                return this.ListAppModulesField;
            }
            set
            {
                this.ListAppModulesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticatorWcf.Module[] ListModules
        {
            get
            {
                return this.ListModulesField;
            }
            set
            {
                this.ListModulesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="App", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities")]
    public partial class App : AuthenticatorWcf.EntityClass
    {
        
        private System.Nullable<bool> AllowExpPassField;
        
        private string AppIdField;
        
        private string AppNameField;
        
        private System.Nullable<int> DaysToExpPassField;
        
        private System.Nullable<int> MaxAttemptsToGetLoginField;
        
        private string PrivateKeyField;
        
        private System.Nullable<int> TokenLifeTimeField;
        
        private string URLActivationUserField;
        
        private string URLResetPassField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AllowExpPass
        {
            get
            {
                return this.AllowExpPassField;
            }
            set
            {
                this.AllowExpPassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppId
        {
            get
            {
                return this.AppIdField;
            }
            set
            {
                this.AppIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName
        {
            get
            {
                return this.AppNameField;
            }
            set
            {
                this.AppNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DaysToExpPass
        {
            get
            {
                return this.DaysToExpPassField;
            }
            set
            {
                this.DaysToExpPassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxAttemptsToGetLogin
        {
            get
            {
                return this.MaxAttemptsToGetLoginField;
            }
            set
            {
                this.MaxAttemptsToGetLoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateKey
        {
            get
            {
                return this.PrivateKeyField;
            }
            set
            {
                this.PrivateKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TokenLifeTime
        {
            get
            {
                return this.TokenLifeTimeField;
            }
            set
            {
                this.TokenLifeTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URLActivationUser
        {
            get
            {
                return this.URLActivationUserField;
            }
            set
            {
                this.URLActivationUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URLResetPass
        {
            get
            {
                return this.URLResetPassField;
            }
            set
            {
                this.URLResetPassField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Module", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities")]
    public partial class Module : AuthenticatorWcf.EntityClass
    {
        
        private AuthenticatorWcf.App AppField;
        
        private string IconField;
        
        private System.Nullable<bool> IsViewField;
        
        private System.DateTime LastUpdateField;
        
        private System.Nullable<bool> ModifyingField;
        
        private string ModuleIdField;
        
        private string ModuleNameField;
        
        private System.Nullable<bool> ReadingField;
        
        private string RoleIdField;
        
        private string StyleField;
        
        private string URLField;
        
        private System.Nullable<bool> WritingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticatorWcf.App App
        {
            get
            {
                return this.AppField;
            }
            set
            {
                this.AppField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icon
        {
            get
            {
                return this.IconField;
            }
            set
            {
                this.IconField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsView
        {
            get
            {
                return this.IsViewField;
            }
            set
            {
                this.IsViewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Modifying
        {
            get
            {
                return this.ModifyingField;
            }
            set
            {
                this.ModifyingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleId
        {
            get
            {
                return this.ModuleIdField;
            }
            set
            {
                this.ModuleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName
        {
            get
            {
                return this.ModuleNameField;
            }
            set
            {
                this.ModuleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Reading
        {
            get
            {
                return this.ReadingField;
            }
            set
            {
                this.ReadingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style
        {
            get
            {
                return this.StyleField;
            }
            set
            {
                this.StyleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL
        {
            get
            {
                return this.URLField;
            }
            set
            {
                this.URLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Writing
        {
            get
            {
                return this.WritingField;
            }
            set
            {
                this.WritingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities")]
    public partial class User : AuthenticatorWcf.EntityClass
    {
        
        private System.Nullable<int> CompanyIdField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string IdField;
        
        private string LastNameField;
        
        private System.DateTime LastUpdateField;
        
        private AuthenticatorWcf.UserAccess[] LoginsField;
        
        private string TypeIdField;
        
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticatorWcf.UserAccess[] Logins
        {
            get
            {
                return this.LoginsField;
            }
            set
            {
                this.LoginsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeId
        {
            get
            {
                return this.TypeIdField;
            }
            set
            {
                this.TypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccess", Namespace="http://schemas.datacontract.org/2004/07/Cenet.Auth.Entities")]
    public partial class UserAccess : AuthenticatorWcf.EntityClass
    {
        
        private System.Nullable<int> AttemptsToGetLoginWrongField;
        
        private System.Nullable<System.DateTime> ExpirationDateField;
        
        private System.Nullable<bool> IsBlockedField;
        
        private System.Nullable<bool> IsVerifiedField;
        
        private System.DateTime LastUpdateField;
        
        private AuthenticatorWcf.Role[] ListRolesField;
        
        private string PassField;
        
        private string RoleIdField;
        
        private AuthenticatorWcf.User UserField;
        
        private System.Nullable<int> UserAccessIdField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AttemptsToGetLoginWrong
        {
            get
            {
                return this.AttemptsToGetLoginWrongField;
            }
            set
            {
                this.AttemptsToGetLoginWrongField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsBlocked
        {
            get
            {
                return this.IsBlockedField;
            }
            set
            {
                this.IsBlockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsVerified
        {
            get
            {
                return this.IsVerifiedField;
            }
            set
            {
                this.IsVerifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticatorWcf.Role[] ListRoles
        {
            get
            {
                return this.ListRolesField;
            }
            set
            {
                this.ListRolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass
        {
            get
            {
                return this.PassField;
            }
            set
            {
                this.PassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticatorWcf.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserAccessId
        {
            get
            {
                return this.UserAccessIdField;
            }
            set
            {
                this.UserAccessIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticatorWcf.IAuthenticator")]
    public interface IAuthenticator
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/ActivateUser", ReplyAction="http://tempuri.org/IAuthenticator/ActivateUserResponse")]
        System.Threading.Tasks.Task<bool> ActivateUserAsync(string tokenActivation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/AutenticateUser", ReplyAction="http://tempuri.org/IAuthenticator/AutenticateUserResponse")]
        System.Threading.Tasks.Task<AuthenticatorWcf.UserAccess> AutenticateUserAsync(string userName, string password, string appId, bool SSO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/AutenticateUserAdmin", ReplyAction="http://tempuri.org/IAuthenticator/AutenticateUserAdminResponse")]
        System.Threading.Tasks.Task<AuthenticatorWcf.UserAccess> AutenticateUserAdminAsync(string UserName, string Password, string AppID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/ForwardActivation", ReplyAction="http://tempuri.org/IAuthenticator/ForwardActivationResponse")]
        System.Threading.Tasks.Task<string> ForwardActivationAsync(string userName, string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/RequestResetPass", ReplyAction="http://tempuri.org/IAuthenticator/RequestResetPassResponse")]
        System.Threading.Tasks.Task<string> RequestResetPassAsync(AuthenticatorWcf.UserAccess userAccess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/SendEmailToNewUsers", ReplyAction="http://tempuri.org/IAuthenticator/SendEmailToNewUsersResponse")]
        System.Threading.Tasks.Task<string> SendEmailToNewUsersAsync(AuthenticatorWcf.UserAccess userAccess);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/ResetPassword", ReplyAction="http://tempuri.org/IAuthenticator/ResetPasswordResponse")]
        System.Threading.Tasks.Task<bool> ResetPasswordAsync(AuthenticatorWcf.UserAccess pass, string tokenReset);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IAuthenticatorChannel : AuthenticatorWcf.IAuthenticator, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AuthenticatorClient : System.ServiceModel.ClientBase<AuthenticatorWcf.IAuthenticator>, AuthenticatorWcf.IAuthenticator
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthenticatorClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthenticatorClient.GetBindingForEndpoint(endpointConfiguration), AuthenticatorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticatorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthenticatorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticatorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthenticatorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> ActivateUserAsync(string tokenActivation)
        {
            return base.Channel.ActivateUserAsync(tokenActivation);
        }
        
        public System.Threading.Tasks.Task<AuthenticatorWcf.UserAccess> AutenticateUserAsync(string userName, string password, string appId, bool SSO)
        {
            return base.Channel.AutenticateUserAsync(userName, password, appId, SSO);
        }
        
        public System.Threading.Tasks.Task<AuthenticatorWcf.UserAccess> AutenticateUserAdminAsync(string UserName, string Password, string AppID)
        {
            return base.Channel.AutenticateUserAdminAsync(UserName, Password, AppID);
        }
        
        public System.Threading.Tasks.Task<string> ForwardActivationAsync(string userName, string appId)
        {
            return base.Channel.ForwardActivationAsync(userName, appId);
        }
        
        public System.Threading.Tasks.Task<string> RequestResetPassAsync(AuthenticatorWcf.UserAccess userAccess)
        {
            return base.Channel.RequestResetPassAsync(userAccess);
        }
        
        public System.Threading.Tasks.Task<string> SendEmailToNewUsersAsync(AuthenticatorWcf.UserAccess userAccess)
        {
            return base.Channel.SendEmailToNewUsersAsync(userAccess);
        }
        
        public System.Threading.Tasks.Task<bool> ResetPasswordAsync(AuthenticatorWcf.UserAccess pass, string tokenReset)
        {
            return base.Channel.ResetPasswordAsync(pass, tokenReset);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthenticator))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IAuthenticator))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthenticator))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.55.170/Cenet.Auth.Service.Wcf/Svc/Authenticator.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IAuthenticator))
            {
                return new System.ServiceModel.EndpointAddress("https://win2019-20.cenet2000/Cenet.Auth.Service.Wcf/Svc/Authenticator.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAuthenticator,
            
            BasicHttpsBinding_IAuthenticator,
        }
    }
}
